spring.jmx:
   enabled: false

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/natale
    username: root
    password: root

  jpa:
     hibernate:
       ddl-auto: none
       naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
     show-sql: true
     properties:
       hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8090

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false
    user:
        name: admin
        password: admin

security.enable-csrf: false

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: nataleManager2
  version: 0.0.1

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
  
logging:
  file: nataleManager.log
  org.hibernate: INFO, DEBUG

 