spring.jmx:
   enabled: false

spring:
  datasource:
    driverClassName: org.postgresql.Driver
#    Heroku Postgresql
    url: jdbc:postgresql://ec2-50-19-127-158.compute-1.amazonaws.com:5432/dfieejidf00mrp
    username: exqfipwskmywjc
    password: 4cbeb460d447a2dbf7ea9612bb2d5f80b82c6c5ab24a95bdc386a1e3398d62ac
#    Local
    

  jpa:
     hibernate:
       ddl-auto: update
       naming:
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
     show-sql: true
     properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
#  security:
#    user:
#      name: admin
#      password: admin
#      roles: USER

server:
  port: 8090



#management endpoints on a separate port
#management:
#  port: 8091
#  security:
#    enabled: false

#default project info followed by actual injected pom-specified values.
project:
  name: NataleManager
  version: 0.0.1

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
  
logging:
  file: nataleManager.log
  org.hibernate: INFO, DEBUG

 